NightSpecter/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('UI/',include('UI.urls')),
]

UI/urls.py
from django.urls import path
from . import views
app_name='UI'
urlpatterns = [
    path('',views.index,name='index'),
    path('<int:group_id>/',views.detail,name='detail'),
    path('<int:group_id>/revise/',views.revise,name='revise'),
    path('<int:group_id>/results/',views.results,name='results')
]

UI/models.py
from django.db import models

# Create your models here.
from django.db import models

class Group(models.Model):
    group_name = models.CharField(max_length=200,verbose_name='作业组成员')
    work_date = models.DateTimeField('作业日期')
    num_workers = models.IntegerField(verbose_name='作业人数')
    def __str__(self):
        return self.group_name


class Tool(models.Model):
    group = models.ForeignKey(Group,on_delete=models.CASCADE)
    num_tools = models.IntegerField(verbose_name='工具数量')
    num_materials = models.IntegerField(verbose_name='材料数量')
    def __str__(self):
        return "工具"+str(self.num_tools)+"；材料"+str(self.num_materials)

class Door(models.Model):
    group = models.ForeignKey(Group,on_delete=models.CASCADE)
    up_door = models.CharField(max_length=200,verbose_name='上道站台')
    down_door = models.CharField(max_length=200,verbose_name='下道站台')
    def __str__(self):
        return "上道："+str(self.up_door)+"；下道："+str(self.down_door)

UI/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse
import datetime
from django.utils import timezone
from .models import Group,Tool
from django.shortcuts import render,get_object_or_404
from django.urls import reverse
from django.http import HttpResponse,HttpResponseRedirect


def index(request):
    today_groups = Group.objects.order_by('-work_date')

    context = {'today_groups': today_groups}
    return render(request,'UI/index.html', context)


def detail(request,group_id):

    group = get_object_or_404(Group,pk=group_id)
    return render(request,'UI/detail.html',{'group':group})

def revise(request,group_id):
    group = get_object_or_404(Group,pk=group_id)
    try:
        selected_tool=group.tool_set.get(pk=request.POST['tool'])
    except (KeyError,Tool.DoesNotExist):
        return render(request,'UI/detail.html',{'group':group,'error_message':"你没有修改！"})
    else:
        selected_tool.num_tools +=10
        selected_tool.save()

        return HttpResponseRedirect(reverse('UI:results',args=(group.id,)))

def results(request , group_id):
    group = get_object_or_404(Group,pk=group_id)
    return render(request,'UI/results.html',{'group':group})

UI/templates/UI/detail.html
<h1>{{group.group_name}}</h1>
{% if error_message %}<p><strong>{{error_message}}</strong></p>{% endif %}
<form action = "{% url 'UI:revise' group.id %}" method='post' >
    {% csrf_token %}
    {% for tool in group.tool_set.all %}
        <input type="radio" name="tool" id = "tool{{forloop.counter}}" value = "{{tool.id}}">
    <label for="tool{{forloop.counter}}">{{tool.num_tools}}</label><br>
    {% endfor %}
    <input type="submit" value="修改">
</form>

UI/templates/UI/index.html
{% if today_groups %}
    <ul>
    {% for group in today_groups %}
        <li>
            <a href="{% url 'UI:detail' group.id %}">{{group.group_name}}</a>
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>今天没有工作组</p>
{% endif %}

UI/templates/UI/results.html
<h1>{{ group.group_name }}</h1>

<ul>
    {% for tool in group.tool_set.all %}
    <li>
        工具--{{tool.num_tools}}件{{tool.num_tools|pluralize}}
    </li>
    {% endfor %}
</ul>
<a href = "{% url 'UI:detail' group.id %}">再次修改？</a>